accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/',views.login, name='login' ),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),

]

products/urls.py
from django.urls import path
from . import views

app_name='products'
urlpatterns = [
    path('<int:pk>/',views.product, name='product'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/',views.delete, name='delete'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),

    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



"""
1. 회원가입을 기능을 구현
2. 로그인 로그아웃 기능 구현
3. 글 CRUD구현 하기 ( 회원의 PK 값을 보유 하고 있어야 함)
4. 프로필 페이지 만들기 / 누구나 관람이 가능하다, 팔로우 기능이 있다.
"""

users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('<int:pk>/like/', views.like, name='like'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('<int:pk>/follow',views.follow, name='follow')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self',symmetrical=False,related_name='follwers')

products/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Products(models.Model):
    title = models.CharField(max_length=(50))
    content = models.TextField()
    add_date= models.DateTimeField(auto_now_add=True)
    edit_date= models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='products_user')

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_products'
    )

users/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import User



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")
    

products/forms.py
from django import forms

from .models import Products


class FormProducts(forms.ModelForm):
    class Meta:
        model = Products
        fields = "__all__"
        exclude = ['user', 'like_users']

accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import login as auth_login , logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.views.decorators.http import require_POST,require_http_methods


# from .forms import CustomUserCreationForm


# Create your views here.

@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_path= request.GET.get('next') or 'index'
            return redirect(next_path)
    else: 
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('index')


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user =form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request,'accounts/signup.html', context)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FormProducts
from .models import Products
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST,require_http_methods

# Create your views here.
@login_required
def product(request,pk):
    products = get_object_or_404(Products,pk=pk)
    context = {'products': products}
    return render(request, 'products/products.html',context )


@login_required
def create(request):
    if request.method == 'POST':
        form = FormProducts(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect('index')
    else:
            form = FormProducts()
    context = { "form":form}
    return render(request, 'products/create.html',context )

@login_required
def update(request, pk):
    product = get_object_or_404(Products,pk=pk)
    if request.method == 'POST':
        form = FormProducts(request.POST, request.FILES,instance=product )
        if form.is_valid():
            form.save()
            return redirect('products:product',pk)
    else:
        form = FormProducts(instance=product)
    context = {'form':form, 'product':product}
    return render(request, 'products/update.html', context)


@login_required
def delete(request, pk):
    deletes = get_object_or_404(Products,pk=pk)
    Products.delete(deletes)
    return redirect('index')

spartamarket/views.py
from django.shortcuts import render
from products.models import Products

def index(request):
    products = Products.objects.all()
    context = {'products':products}
    return render(request, 'index.html', context)

users/views.py
from django.shortcuts import render,get_object_or_404, redirect
from accounts.models import User
from products.models import Products
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


# profile
@login_required
def profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    UserProducts = user.products_user.all()
    Userlikes = user.like_products.all()
    Userfollows = user.follwers.all()
    context = {'user': user, 'UserProducts': UserProducts, 'Userlikes':Userlikes,'Userfollows':Userfollows }
    return render(request, 'users/profile.html', context)


@login_required
def like(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Products, pk=pk)
        if product.like_users.filter(pk=request.user.pk).exists():
            product.like_users.remove(request.user)
        else:
            product.like_users.add(request.user)
        return redirect('index')
    return redirect('accounts:login')

@login_required
def follow(request, pk):
    if request.user.is_authenticated:
        menber = get_object_or_404(get_user_model(), pk=pk)
        if menber != request.user:
            if menber.follwers.filter(pk=request.user.pk).exists():
                menber.follwers.remove(request.user)
            else:
                menber.follwers.add(request.user)
        return redirect('users:profile', menber.pk)
    return redirect('account:login')

accounts/templates/accounts/login.html
{% extends 'base.html'%}

{% block content %}

<div class="card mx-auto" style="width: 20rem; margin-top: 20%;">
    <div class="card-header text-center">
        <h1>로그인</h1>
    </div>
    <div class="card-body">
        <form action="" method="POST" >
            {% csrf_token %}
            <p class="mb-3">
                <label for="id_username" class="form-label">Username:</label>
                <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" class="form-control">
            </p>
            <p class="mb-3">
                <label for="id_password" class="form-label" >Password:</label>
                <input type="password" name="password" autocomplete="current-password" required="" id="id_password" class="form-control">
            </p>
            <button type="submit" class="btn btn-primary d-grid mx-auto">로그인</button>
        </form>
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html'%}

{% block content %}

<h1>회원가입</h1>

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
<br>
    <div>
        <label for="id_username">Username:</label>
        <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
        <span class="helptext"> 회원님의 이름(ID)를 입력하세요 </span>
    </div>
<br>
    <div>
        <label for="id_password1">Password:</label>
        <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
        <span class="helptext"></span>
<br>
<br>
        <label for="id_password2">Password confirmation:</label>
        <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
        <span class="helptext">확인을 위해 이전과 동일한 암호를 입력하세요.</span>
        </div>
<br>
    <div>
    <ul>
        <li>비밀번호는 다른 개인정보와 너무 비슷할 수 없습니다.</li>
        <li>비밀번호는 8자 이상이어야 합니다.</li>
        <li>비밀번호는 일반적으로 사용되는 비밀번호일 수 없습니다.</li>
        <li>비밀번호가 완전히 숫자일 수는 없습니다.</li>
    </ul>
    <div>
        <button type="submit">회원가입</button>
</form>



{% endblock %}

products/templates/products/create.html
{% extends 'base.html' %}

{% block content %}

<h1> products create </h1>
<form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">게시물 올리기</button>
</form>

{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}

{% block content %}

<h1>{{products.title}}</h1>

<h7>작성자 :
    <a href="{% url 'users:profile' products.user_id %}">'{{ products.user }}'의 프로필 </a>
</h7>
<hr>
<h7>작성일 : {{ products.add_date|date:'Y-m-d' }}</h7>
{% if products.image %}
<hr>
<img src="{{ products.image.url }}" alt="">
{% endif %}
<hr>
<div style="height: 400px;">
    <h5>내용</h5>
    <br>
    <P>{{ products.content }}</P>
</div>
    {% if products.user_id == user.id %}
<a href="{% url 'products:update' products.pk %}">수정</a>
<hr>
<form action="{% url 'products:delete' products.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">삭제</button>
</form>
{% endif %}
<hr>
<a href="{% url 'index' %}"> 홈으로 가기  </a>

{% endblock %}

products/templates/products/update.html
{% extends 'base.html' %}

{% block content %}

<h1> products update </h1>
<form action="{% url 'products:update' product.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">게시물 수정하기</button>
</form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
</head>

<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'carrot.jpg' %}" alt="SpartaMrket" width="30" height="24">
            </a>
            <div class="d-flex">
                <ul class="nav justify-content-end">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'users:profile' request.user.pk %}" class="nav-link active">'{{ request.user.username }}'의 프로필 </a>
                    </li>
                    <li class="nav-item">
                        <form class="nav-link active" action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">로그아웃</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:signup' %}">회원가입</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-md">
        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>SpartaMrket</h1>
<br>

<a href="{% url 'products:create'%}"> 물건 등록하기 </a>

<hr>
<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for product in products %}
    <div class="col" >
        <div class="card h-100" style="height: 100%">
            <a href="{% url 'products:product' product.pk %}">
                {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{product.image}}"
                >
                {% else %}
                <img src="http://placehold.it/150X150" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{product.title}}</h5>
                </div>
            </a>
            <form action="{% url 'users:like' product.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in product.like_users.all %}
                <button type="submit">찜하기 취소</button>
                {% else %}
                <button type="submit"> 찜하기 </button>
                {% endif %}
            </form>
        </div>
    </div>
    {% endfor%}

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h2>'{{user.username}}' 님의 프로필</h2>
<br>
<hr>
<h5>가입일 : {{user.date_joined|date:'Y-m-d' }}</h5>
<hr>
{% if request.user.pk != user.pk %}
<h5> 팔로우 </h5>
<form action="{% url 'users:follow' user.pk%}"method="POST">
    {% csrf_token %}
    {% if request.user in user.follwers.all %}
    <button type="submit"> 언팔로우 </button>
    {% else %}
    <button type="submit"> 팔로우 </button>
    {% endif %}
</form>
<hr>
{% endif %}

<h5>내가 등록한 물품들 </h5>
<div class="row row-cols-1 row-cols-md-4 g-4">
{% for UserProduct in UserProducts %}
<div class="col" style="width: 20%;">
    <div class="card">
        <a href="{% url 'products:product' UserProduct.pk %}">
            {% if UserProduc.image %}
            <img src="{{ UserProduct.image.url }}" class="card-img-top">
            {% else %}
            <img src="http://placehold.it/150X150" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <p class="card-title" style="font-size: 15px;">{{UserProduct.title}}</p>
            </div>
        </a>
    </div>
</div>
{% endfor %}
</div>
<hr>

<h5>내가 찜함 물품들 </h5>

<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for Userlike in Userlikes %}
    <div class="col" style="width: 20%;">
        <div class="card">
            <a href="{% url 'products:product' Userlike.user_id %}">
                {% if Userlike.image %}
                <img src="{{ Userlike.image.url }}" class="card-img-top">
                {% else %}
                <img src="http://placehold.it/150X150" class="card-img-top">
                {% endif %}
                <div class="card-body">
                    <p class="card-title" style="font-size: 15px;">{{Userlike.title}}</p>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
    </div>





{% endblock %}